// ui-ops/src/app/app.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectorRef, Component, OnInit, inject } from "@angular/core";
import { DomSanitizer, SafeResourceUrl } from "@angular/platform-browser";

import { AppModel, JourneyModel, Persona, PortalService, WhoAmI } from "./portal.service";

// The Ops Journey shell. Deliberately THIN, exactly like the React RM shell: a persona switcher and
// a tabbed set of same-origin iframes over the portal BFF. Same BFF, different host framework - the
// whole point of the two-shell demo. Identity, proxying and journey config live in the BFF.
const JOURNEY_KEY = "ops";

@Component({
  selector: "app-root",
  standalone: true,
  imports: [CommonModule],
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"],
})
export class AppComponent implements OnInit {
  private portal = inject(PortalService);
  private sanitizer = inject(DomSanitizer);
  private changeDetector = inject(ChangeDetectorRef);

  journey: JourneyModel | null = null;
  personas: Persona[] = [];
  me: WhoAmI | null = null;
  active: AppModel | null = null;
  frameUrl: SafeResourceUrl | null = null;
  error = "";

  ngOnInit(): void {
    this.portal.journeys().subscribe({
      next: (journeys) => {
        this.journey = journeys.find((j) => j.key === JOURNEY_KEY) ?? journeys[0] ?? null;
        this.select(this.journey?.apps[0] ?? null);
        this.changeDetector.detectChanges();
      },
      error: (e: unknown) => (this.error = this.message(e)),
    });
    this.portal.personas().subscribe({
      next: (personas) => {
        this.personas = personas;
        this.changeDetector.detectChanges();
      },
      error: () => undefined,
    });
    this.portal.whoami().subscribe({
      next: (who) => {
        this.me = who;
        this.changeDetector.detectChanges();
      },
      error: () => undefined,
    });
  }

  select(app: AppModel | null): void {
    this.active = app;
    // The app UI is same-origin (proxied), so a relative URL is safe; Angular still requires it be
    // marked trusted to bind to an iframe src.
    this.frameUrl = app ? this.sanitizer.bypassSecurityTrustResourceUrl(app.ui_base) : null;
  }

  onPersona(id: string): void {
    this.portal.setPersona(id).subscribe({
      next: (who) => {
        this.me = who;
        // Force the active iframe to reload so the embedded apps pick up the new identity (their
        // next API call carries the updated portal cookie).
        const current = this.active;
        this.select(null);
        this.changeDetector.detectChanges();
        setTimeout(() => {
          this.select(current);
          this.changeDetector.detectChanges();
        }, 0);
      },
      error: (e: unknown) => (this.error = this.message(e)),
    });
  }

  private message(e: unknown): string {
    return e instanceof Error ? e.message : String(e);
  }
}

<main class="shell" data-demo="ops-journey" *ngIf="!error; else errorTpl">
  <ng-container *ngIf="journey; else loadingTpl">
    <header class="topbar">
      <div class="brand">
        <span class="tier">OPS</span>
        <div>
          <h1>{{ journey.label }}</h1>
          <p>{{ journey.blurb }}</p>
        </div>
      </div>
      <div class="identity">
        <label class="persona" *ngIf="personas.length && me">
          Demo identity
          <select data-demo="persona-selector" [value]="me.persona" (change)="onPersona($any($event.target).value)">
            <option *ngFor="let p of personas" [value]="p.id">{{ p.id }} · {{ p.subject }}</option>
          </select>
        </label>
        <span data-demo="verified-identity" class="who" *ngIf="me" [title]="me.principals.join(', ')">
          {{ me.subject }} &#64; {{ me.tenant }}
        </span>
      </div>
    </header>

    <nav class="tabs">
      <button
        *ngFor="let a of journey.apps"
        [attr.data-demo]="'app-tab-' + a.id"
        class="tab"
        [class.active]="active?.id === a.id"
        (click)="select(a)"
      >
        {{ a.label }}
      </button>
    </nav>

    <section class="stage">
      <iframe data-demo="embedded-app" *ngIf="frameUrl" [src]="frameUrl" [title]="active?.label || ''" class="frame"></iframe>
    </section>
  </ng-container>
</main>

<ng-template #loadingTpl><p class="loading">Loading journey…</p></ng-template>
<ng-template #errorTpl>
  <p class="error">Portal error: {{ error }}. Is the BFF running on :8110?</p>
</ng-template>

// ui-rm/app/page.tsx
"use client";

// The RM Journey shell. Deliberately THIN: it renders a persona switcher and a tabbed set of
// same-origin iframes over the portal BFF, and nothing else. All identity, proxying and config
// live in the BFF; the shell just composes. Its small size IS the point - it is the evidence that
// the agents drop into an existing React app with a couple of hundred lines of host code.

import { useCallback, useEffect, useState } from "react";

import { listJourneys, listPersonas, setPersona, whoami } from "@/lib/api";
import type { JourneyModel, Persona, WhoAmI } from "@/lib/types";

const JOURNEY_KEY = process.env.NEXT_PUBLIC_JOURNEY || "rm";

export default function Page() {
  const [journey, setJourney] = useState<JourneyModel | null>(null);
  const [personas, setPersonas] = useState<Persona[]>([]);
  const [me, setMe] = useState<WhoAmI | null>(null);
  const [activeApp, setActiveApp] = useState<string>("");
  const [reloadKey, setReloadKey] = useState(0);
  const [error, setError] = useState<string>("");

  useEffect(() => {
    (async () => {
      try {
        const [journeys, ps, who] = await Promise.all([listJourneys(), listPersonas(), whoami()]);
        const found = journeys.find((j) => j.key === JOURNEY_KEY) ?? journeys[0] ?? null;
        setJourney(found);
        setActiveApp(found?.apps[0]?.id ?? "");
        setPersonas(ps);
        setMe(who);
      } catch (e) {
        setError(String(e));
      }
    })();
  }, []);

  const onPersona = useCallback(async (id: string) => {
    try {
      setMe(await setPersona(id));
      // The embedded apps read identity from the portal cookie on their next API call, so a fresh
      // iframe load picks up the new persona everywhere at once.
      setReloadKey((k) => k + 1);
    } catch (e) {
      setError(String(e));
    }
  }, []);

  if (error) {
    return (
      <main className="shell">
        <p className="error">Portal error: {error}. Is the BFF running on :8110?</p>
      </main>
    );
  }
  if (!journey) {
    return (
      <main className="shell">
        <p className="loading">Loading journey…</p>
      </main>
    );
  }

  const app = journey.apps.find((a) => a.id === activeApp) ?? journey.apps[0];

  return (
    <main className="shell" data-demo="rm-journey">
      <header className="topbar">
        <div className="brand">
          <span className="tier">RM</span>
          <div>
            <h1>{journey.label}</h1>
            <p>{journey.blurb}</p>
          </div>
        </div>
        <div className="identity">
          {personas.length > 0 && me && (
            <label className="persona">
              Demo identity{" "}
              <select
                data-demo="persona-selector"
                value={me.persona}
                onChange={(e) => onPersona(e.target.value)}
              >
                {personas.map((p) => (
                  <option key={p.id} value={p.id}>
                    {p.id} · {p.subject}
                  </option>
                ))}
              </select>
            </label>
          )}
          {me && (
            <span data-demo="verified-identity" className="who" title={me.principals.join(", ")}>
              {me.subject} @ {me.tenant}
            </span>
          )}
        </div>
      </header>

      <nav className="tabs">
        {journey.apps.map((a) => (
          <button
            key={a.id}
            data-demo={`app-tab-${a.id}`}
            className={a.id === app.id ? "tab active" : "tab"}
            onClick={() => setActiveApp(a.id)}
          >
            {a.label}
          </button>
        ))}
      </nav>

      <section className="stage">
        <iframe
          key={`${app.id}-${reloadKey}`}
          data-demo="embedded-app"
          title={app.label}
          src={app.ui_base}
          className="frame"
        />
      </section>
    </main>
  );
}
